begin;

insert into public.mkt_dim_market_event_type (
  event_type,
  event_area,
  display_label,
  short_label,
  description,
  metric_previous_label,
  metric_current_label,
  metric_change_label,
  value_format,
  change_format,
  direction_semantics,
  header_variant,
  icon_name,
  accent_token,
  chart_annotation_label,
  appears_in_intraday_radar,
  creates_client_signal,
  default_sort_order,
  presentation_config
)
values
  (
    'chain_available_store_count_dropped',
    'availability',
    'AVAILABLE STORE COUNT DROPPED',
    'Availability drop',
    'The product lost online availability in monitored stores compared with the previous closed day.',
    'Previous available stores',
    'Current available stores',
    'Store change',
    'number',
    'number',
    'negative_bad',
    'availability',
    'circle-alert',
    'danger',
    'Availability drop',
    true,
    false,
    25,
    '{"change_visual":"market_direction","show_header_metrics":true,"header_metric_mode":"available_store_count","llm_guidance":"Explain this as a net chain-level availability drop for the product. Use only observed store availability evidence. Mention lost stores and recovered stores when present. Do not imply sales, demand, revenue, market share, or customer behavior.","evidence_sections":[{"key":"lost_locations","label":"New unavailable stores"},{"key":"recovered_locations","label":"Recovered stores"}]}'::jsonb
  ),
  (
    'chain_available_store_count_recovered',
    'availability',
    'AVAILABLE STORE COUNT RECOVERED',
    'Availability recovered',
    'The product recovered online availability in monitored stores compared with the previous closed day.',
    'Previous available stores',
    'Current available stores',
    'Store change',
    'number',
    'number',
    'positive_good',
    'availability',
    'circle-check',
    'success',
    'Availability recovered',
    true,
    false,
    26,
    '{"change_visual":"market_direction","show_header_metrics":true,"header_metric_mode":"available_store_count","llm_guidance":"Explain this as a net chain-level availability recovery for the product. Use only observed store availability evidence. Mention recovered stores and lost stores when present. Do not imply sales, demand, revenue, market share, or customer behavior.","evidence_sections":[{"key":"recovered_locations","label":"Recovered stores"},{"key":"lost_locations","label":"New unavailable stores"}]}'::jsonb
  ),
  (
    'store_offer_became_unavailable',
    'availability',
    'STORE OFFER BECAME UNAVAILABLE',
    'Store unavailable',
    'The product offer changed from available to unavailable in one monitored store.',
    'Previous source quantity',
    'Current source quantity',
    'Quantity change',
    'number',
    'number',
    'negative_bad',
    'availability',
    'circle-alert',
    'danger',
    'Store unavailable',
    true,
    false,
    27,
    '{"change_visual":"market_direction","show_header_metrics":true,"header_metric_mode":"source_available_quantity","llm_guidance":"Explain this as a store-level availability loss for one monitored store. Use the store name and source available quantity transition when present. Do not extrapolate to sales, demand, or chain-wide availability.","evidence_sections":[{"key":"location_name","label":"Store"},{"key":"previous_source_available_quantity","label":"Previous source quantity"},{"key":"current_source_available_quantity","label":"Current source quantity"}]}'::jsonb
  ),
  (
    'store_offer_became_available',
    'availability',
    'STORE OFFER BECAME AVAILABLE',
    'Store available',
    'The product offer changed from unavailable to available in one monitored store.',
    'Previous source quantity',
    'Current source quantity',
    'Quantity change',
    'number',
    'number',
    'positive_good',
    'availability',
    'circle-check',
    'success',
    'Store available',
    true,
    false,
    28,
    '{"change_visual":"market_direction","show_header_metrics":true,"header_metric_mode":"source_available_quantity","llm_guidance":"Explain this as a store-level availability recovery for one monitored store. Use the store name and source available quantity transition when present. Do not extrapolate to sales, demand, or chain-wide availability.","evidence_sections":[{"key":"location_name","label":"Store"},{"key":"previous_source_available_quantity","label":"Previous source quantity"},{"key":"current_source_available_quantity","label":"Current source quantity"}]}'::jsonb
  )
on conflict (event_type) do update
set event_area = excluded.event_area,
    display_label = excluded.display_label,
    short_label = excluded.short_label,
    description = excluded.description,
    metric_previous_label = excluded.metric_previous_label,
    metric_current_label = excluded.metric_current_label,
    metric_change_label = excluded.metric_change_label,
    value_format = excluded.value_format,
    change_format = excluded.change_format,
    direction_semantics = excluded.direction_semantics,
    header_variant = excluded.header_variant,
    icon_name = excluded.icon_name,
    accent_token = excluded.accent_token,
    chart_annotation_label = excluded.chart_annotation_label,
    appears_in_intraday_radar = excluded.appears_in_intraday_radar,
    creates_client_signal = excluded.creates_client_signal,
    default_sort_order = excluded.default_sort_order,
    presentation_config = excluded.presentation_config,
    updated_at = now();

update public.mkt_dim_market_event_type
set appears_in_intraday_radar = false,
    creates_client_signal = false,
    is_active = false,
    description = 'Legacy aggregate availability state. Replaced by transition-based availability events.',
    presentation_config = coalesce(presentation_config, '{}'::jsonb) || '{"legacy":true}'::jsonb,
    updated_at = now()
where event_type = 'listed_unavailable';

commit;
