-- Market Watch auth/security baseline.
-- Idempotent by design: safe to run repeatedly in phase 0 environments.

create table if not exists public.auth_clients (
  id bigint generated by default as identity primary key,
  client_key text not null unique,
  name text not null,
  market text not null default 'CR',
  mode text not null default 'customer',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint auth_clients_status_ck check (status in ('active', 'inactive')),
  constraint auth_clients_mode_ck check (mode in ('customer', 'internal', 'demo'))
);

create table if not exists public.auth_roles (
  id text primary key,
  label text not null,
  scope text not null,
  description text not null default '',
  created_at timestamptz not null default now(),
  constraint auth_roles_scope_ck check (scope in ('system', 'client'))
);

create table if not exists public.auth_permissions (
  id text primary key,
  label text not null,
  description text not null default ''
);

create table if not exists public.auth_role_permissions (
  role_id text not null references public.auth_roles(id) on delete cascade,
  permission_id text not null references public.auth_permissions(id) on delete cascade,
  primary key (role_id, permission_id)
);

create table if not exists public.auth_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  email text not null unique,
  display_name text not null,
  password_hash text not null,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint auth_users_status_ck check (status in ('active', 'inactive', 'locked'))
);

create table if not exists public.auth_user_roles (
  user_id bigint not null references public.auth_users(id) on delete cascade,
  role_id text not null references public.auth_roles(id) on delete restrict,
  primary key (user_id, role_id)
);

create table if not exists public.auth_user_clients (
  user_id bigint not null references public.auth_users(id) on delete cascade,
  client_id bigint not null references public.auth_clients(id) on delete cascade,
  is_default boolean not null default false,
  primary key (user_id, client_id)
);

create table if not exists public.auth_sessions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.auth_users(id) on delete cascade,
  session_token_hash text not null unique,
  active_client_id text,
  active_role_id text references public.auth_roles(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz
);

alter table public.auth_sessions
  add column if not exists active_role_id text references public.auth_roles(id) on delete set null;

create table if not exists public.auth_audit_log (
  id bigint generated by default as identity primary key,
  user_id bigint references public.auth_users(id) on delete set null,
  client_id bigint references public.auth_clients(id) on delete set null,
  action text not null,
  subject_type text not null,
  subject_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists auth_sessions_token_hash_idx on public.auth_sessions(session_token_hash);
create index if not exists auth_sessions_user_active_idx on public.auth_sessions(user_id, expires_at) where revoked_at is null;
create index if not exists auth_user_clients_client_idx on public.auth_user_clients(client_id);
create index if not exists auth_audit_log_created_idx on public.auth_audit_log(created_at desc);

insert into public.auth_clients (id, client_key, name, market, mode, status)
values (1, 'datasyncsa', 'DataSyncSA', 'CR', 'internal', 'active')
on conflict (id) do update set
  client_key = excluded.client_key,
  name = excluded.name,
  market = excluded.market,
  mode = excluded.mode,
  status = excluded.status,
  updated_at = now();

select setval(
  pg_get_serial_sequence('public.auth_clients', 'id'),
  greatest((select coalesce(max(id), 1) from public.auth_clients), 1)
);

insert into public.auth_roles (id, label, scope, description)
values
  ('system-admin', 'Administrador del sistema', 'system', 'Control total de configuracion, seguridad y datos del portal.'),
  ('system-user', 'Operador del sistema', 'system', 'Operacion interna sin administracion completa de seguridad.'),
  ('client-admin', 'Administrador del cliente', 'client', 'Administra usuarios y configuracion dentro de su cliente.'),
  ('client-viewer', 'Usuario del cliente', 'client', 'Consulta datos, senales y evidencia de su cliente.')
on conflict (id) do update set
  label = excluded.label,
  scope = excluded.scope,
  description = excluded.description;

insert into public.auth_permissions (id, label, description)
values
  ('auth:users:manage', 'Administrar usuarios', 'Crear, editar y desactivar usuarios.'),
  ('auth:roles:manage', 'Administrar roles', 'Ver y mantener roles y permisos.'),
  ('auth:clients:manage', 'Administrar clientes', 'Ver y mantener clientes/tenants.'),
  ('analytics:dashboards:read', 'Leer dashboards', 'Acceder al menu de dashboards.'),
  ('analytics:reports:read', 'Leer reportes', 'Acceder al menu de reportes.'),
  ('operations:campaigns:read', 'Leer campanas', 'Acceder al menu de campanas.'),
  ('operations:catalogs:read', 'Leer catalogos', 'Acceder al menu de catalogos.'),
  ('operations:monitored-products:read', 'Leer productos monitoreados', 'Acceder al menu de productos monitoreados.'),
  ('operations:competitors:read', 'Leer competidores', 'Acceder al menu de competidores.'),
  ('operations:runs:read', 'Leer corridas', 'Acceder al menu de corridas.'),
  ('settings:integrations:read', 'Leer integraciones', 'Acceder al menu de integraciones.'),
  ('signals:read', 'Leer senales', 'Consultar senales ejecutivas.'),
  ('signals:evidence:read', 'Leer evidencia', 'Consultar evidencia de senales.'),
  ('benchmarks:read', 'Leer benchmarks', 'Consultar comparativos de marca y cadena.'),
  ('sku:read', 'Leer SKU', 'Consultar detalle de SKU.'),
  ('events:read', 'Leer eventos', 'Consultar eventos de mercado.')
on conflict (id) do update set
  label = excluded.label,
  description = excluded.description;

insert into public.auth_role_permissions (role_id, permission_id)
select 'system-admin', id from public.auth_permissions
on conflict do nothing;

insert into public.auth_role_permissions (role_id, permission_id)
values
  ('system-user', 'signals:read'),
  ('system-user', 'signals:evidence:read'),
  ('system-user', 'benchmarks:read'),
  ('system-user', 'sku:read'),
  ('system-user', 'events:read'),
  ('system-user', 'analytics:dashboards:read'),
  ('system-user', 'analytics:reports:read'),
  ('system-user', 'operations:campaigns:read'),
  ('system-user', 'operations:catalogs:read'),
  ('system-user', 'operations:monitored-products:read'),
  ('system-user', 'operations:competitors:read'),
  ('system-user', 'operations:runs:read'),
  ('system-user', 'settings:integrations:read'),
  ('client-admin', 'auth:users:manage'),
  ('client-admin', 'signals:read'),
  ('client-admin', 'signals:evidence:read'),
  ('client-admin', 'benchmarks:read'),
  ('client-admin', 'sku:read'),
  ('client-admin', 'events:read'),
  ('client-admin', 'analytics:dashboards:read'),
  ('client-admin', 'analytics:reports:read'),
  ('client-admin', 'operations:campaigns:read'),
  ('client-admin', 'operations:catalogs:read'),
  ('client-admin', 'operations:monitored-products:read'),
  ('client-admin', 'operations:competitors:read'),
  ('client-admin', 'operations:runs:read'),
  ('client-viewer', 'signals:read'),
  ('client-viewer', 'signals:evidence:read'),
  ('client-viewer', 'benchmarks:read'),
  ('client-viewer', 'sku:read'),
  ('client-viewer', 'events:read'),
  ('client-viewer', 'analytics:dashboards:read'),
  ('client-viewer', 'analytics:reports:read'),
  ('client-viewer', 'operations:runs:read')
on conflict do nothing;

insert into public.auth_users (id, username, email, display_name, password_hash, status)
values (
  1,
  'acartin',
  'acartin@market-watch.local',
  'acartin',
  'pbkdf2_sha256$260000$vAcIV06me30AYkDZlvwP812f$nI3w1F5oUSHkKxNcVkb6UNlHDhtV4Vw7UpgoYKdCO1A',
  'active'
)
on conflict (id) do update set
  username = excluded.username,
  email = excluded.email,
  display_name = excluded.display_name,
  password_hash = excluded.password_hash,
  status = excluded.status,
  updated_at = now();

select setval(
  pg_get_serial_sequence('public.auth_users', 'id'),
  greatest((select coalesce(max(id), 1) from public.auth_users), 1)
);

insert into public.auth_user_roles (user_id, role_id)
values (1, 'system-admin')
on conflict do nothing;

insert into public.auth_user_clients (user_id, client_id, is_default)
values (1, 1, true)
on conflict (user_id, client_id) do update set is_default = excluded.is_default;
